################################################################################
# Cetacean.excretion.global project
# Lola Gilbert lola.gilbert@univ-lr.fr
#
# December 2021
# _targets.R
#
# Script decomposing with all steps of the analysis with target
################################################################################

library("targets")

# Source all functions contained in all files in the R directory
lapply(list.files(here::here("R"),
                  recursive = TRUE, full.names = T),
       source)


list(
  
  ##############################################################################
  ############### compute ratio of cetacean abundances where needed ############
  ################# refers to functions of 00_ratio_abundances.R ###############
  
  # define data files (only ASI, SCANSIII, REMMOA ANTGUY and Indian ocean)
  tar_target(data_ASI_file,
             "data/abundance_surveys/ASI/ASI_Total_Sighting_Exchange_data.xlsx",
             format = "file"), # ASI - Mediterranean Sea
  tar_target(data_SCANSIII_air_file,
             "data/abundance_surveys/SCANSIII/aerial_sightings_by_block.xlsx",
             format = "file"), # SCANS III - air survey
  tar_target(data_SCANSIII_ship_file,
             "data/abundance_surveys/SCANSIII/ship_sightings_by_block.xlsx",
             format = "file"), # SCANS III - ship survey
  tar_target(data_REMMOA_ANTGUY_file,
             "data/abundance_surveys/REMMOA_ANTGUY/Obs-Effort_ANTGUY2017_RapportFinal.xlsx",
             format = "file"), # REMMOA Antilles & Guyana 
  tar_target(data_REMMOA_Ind_file,
             "data/abundance_surveys/REMMOA_Indian/Sighting_OI_REMMOA_LEG_070721.csv",
             format = "file"), # REMMOA indian ocean
  # load data (only ASI, SCANSIII, REMMOA ANTGUY and Indian ocean)
  tar_target(data_ASI, load_xl(data_ASI_file)),
  tar_target(data_SCANS_air, load_xl(data_SCANSIII_air_file)),
  tar_target(data_SCANS_ship, load_xl(data_SCANSIII_ship_file)),
  tar_target(data_REMMOA_ANTGUY, load_xl(data_REMMOA_ANTGUY_file)),
  tar_target(data_REMMOA_Ind, load_csv(data_REMMOA_Ind_file)),
  #### compute ratios separately
  # for areas associated with files 
  tar_target(ratio_ASI, compute_ratio_ASI(data_ASI)),
  tar_target(ratio_NEA, compute_ratio_NEA(data_SCANS_air, data_SCANS_ship)), 
  tar_target(ratio_REMMOA_ANTGUY, compute_ratio_REMMOA_ANTGUY(data_REMMOA_ANTGUY)), 
  tar_target(ratio_REMMOA_Ind, compute_ratio_REMMOA_Ind(data_REMMOA_Ind)), 
  # and for areas not associated with files
  tar_target(ratio_REMMOA_FPol, compute_ratio_REMMOA_FPol()),
  tar_target(ratio_REMMOA_NCal, compute_ratio_REMMOA_NCal()),
  tar_target(ratio_REMMOA_WFu, compute_ratio_REMMOA_WFu()),
  tar_target(ratio_GoMex, compute_ratio_GoMex()),
  tar_target(ratio_Hawaii, compute_ratio_Hawaii()),
  tar_target(ratio_Calif, compute_ratio_Calif()), 
  #### bind ratio tibbles (two: one for REMMOA with groups and one other with 
  # just species)
  tar_target(ratio_full_REMMOAs, bind_ratio_REMMOAs(ratio_REMMOA_ANTGUY, 
                                                    ratio_REMMOA_Ind, 
                                                    ratio_REMMOA_FPol, 
                                                    ratio_REMMOA_NCal,
                                                    ratio_REMMOA_WFu)), 
  tar_target(ratio_full_others, bind_ratio_others(ratio_NEA, 
                                                    ratio_ASI, 
                                                    ratio_GoMex, 
                                                    ratio_Hawaii,
                                                    ratio_Calif)), 
  
  ##############################################################################
  ###################### generate population abundance data ####################
  ################# refers to functions of 01_abundance_data.R #################
  
  # generate original data sets from reports and articles, sp per sp
  tar_target(original_tib_Bala_acu, data_from_data_Bala_acu()), 
  tar_target(original_tib_Bala_bor, data_from_data_Bala_bor()), 
  tar_target(original_tib_Bala_ede, data_from_data_Bala_ede()), 
  tar_target(original_tib_Bala_mus, data_from_data_Bala_mus()), 
  tar_target(original_tib_Bala_phy, data_from_data_Bala_phy()),  
  tar_target(original_tib_Fere_att, data_from_data_Fere_att()), 
  tar_target(original_tib_Glob_mac, data_from_data_Glob_mac()), 
  tar_target(original_tib_Glob_mel, data_from_data_Glob_mel()),
  tar_target(original_tib_Gram_gri, data_from_data_Gram_gri()),
  tar_target(original_tib_Kogi_spp, data_from_data_Kogi_spp()),
  tar_target(original_tib_Lage_acu, data_from_data_Lage_acu()),
  tar_target(original_tib_Lage_alb, data_from_data_Lage_alb()),
  tar_target(original_tib_Lage_hos, data_from_data_Lage_hos()),
  tar_target(original_tib_Lage_obl, data_from_data_Lage_obl()),
  tar_target(original_tib_Liss_bor, data_from_data_Liss_bor()),
  tar_target(original_tib_Mega_nov, data_from_data_Mega_nov()),
  tar_target(original_tib_Orci_orc, data_from_data_Orci_orc()),
  tar_target(original_tib_Pepo_ele, data_from_data_Pepo_ele()),
  tar_target(original_tib_Phoc_dal, data_from_data_Phoc_dal()),
  tar_target(original_tib_Phoc_pho, data_from_data_Phoc_pho()),
  tar_target(original_tib_Phys_mac, data_from_data_Phys_mac()),
  tar_target(original_tib_Pseu_cra, data_from_data_Pseu_cra()),
  tar_target(original_tib_Sota_gui, data_from_data_Sota_gui()),
  tar_target(original_tib_Sten_att, data_from_data_Sten_att()),
  tar_target(original_tib_Sten_cly, data_from_data_Sten_cly()),
  tar_target(original_tib_Sten_fro, data_from_data_Sten_fro()),
  tar_target(original_tib_Sten_lon, data_from_data_Sten_lon()),
  tar_target(original_tib_Sten_bre, data_from_data_Sten_bre()),
  tar_target(original_tib_Turs_tru, data_from_data_Turs_tru()),
  # build tibbles with our format
  tar_target(abund_Bala_acu, build_sp_tib(original_tib_Bala_acu, 
                                          "Balaenoptera acutorostrata", 
                                          "Bala_acu")), 
  tar_target(abund_Bala_bor, build_sp_tib(original_tib_Bala_bor, 
                                          "Balaenoptera borealis", 
                                          "Bala_bor")), 
  tar_target(abund_Bala_ede, build_sp_tib(original_tib_Bala_ede, 
                                          "Balaenoptera edeni", 
                                          "Bala_ede")), 
  tar_target(abund_Bala_mus, build_sp_tib(original_tib_Bala_mus, 
                                          "Balaenoptera musculus", 
                                          "Bala_mus")), 
  tar_target(abund_Bala_phy, build_sp_tib(original_tib_Bala_phy, 
                                          "Balaenoptera physalus", 
                                          "Bala_phy")),
  tar_target(abund_Fere_att, build_sp_tib(original_tib_Fere_att, 
                                          "Feresa attenuata", 
                                          "Fere_att")),
  tar_target(abund_Glob_mac, build_sp_tib(original_tib_Glob_mac, 
                                          "Globicephala macrorhynchus", 
                                          "Glob_mac")),
  tar_target(abund_Glob_mel, build_sp_tib(original_tib_Glob_mel, 
                                          "Globicephala melas", 
                                          "Glob_mel")),
  tar_target(abund_Gram_gri, build_sp_tib(original_tib_Gram_gri, 
                                          "Grampus griseus", 
                                          "Gram_gri")),
  tar_target(abund_Kogi_spp, build_sp_tib(original_tib_Kogi_spp, 
                                          "Kogia spp", 
                                          "Kogi_spp")),
  tar_target(abund_Lage_acu, build_sp_tib(original_tib_Lage_acu, 
                                          "Lagenorhynchus acutus", 
                                          "Lage_acu")),
  tar_target(abund_Lage_alb, build_sp_tib(original_tib_Lage_alb, 
                                          "Lagenorhynchus albirostris", 
                                          "Lage_alb")),
  tar_target(abund_Lage_hos, build_sp_tib(original_tib_Lage_hos, 
                                          "Lagenorhynchus hosei", 
                                          "Lage_hos")),
  tar_target(abund_Lage_obl, build_sp_tib(original_tib_Lage_obl, 
                                          "Lagenorhynchus obliquidens", 
                                          "Lage_obl")),
  tar_target(abund_Liss_bor, build_sp_tib(original_tib_Liss_bor, 
                                          "Lissodelphis borealis", 
                                          "Liss_bor")),
  tar_target(abund_Mega_nov, build_sp_tib(original_tib_Mega_nov, 
                                          "Megaptera novaeangliae", 
                                          "Mega_nov")),
  tar_target(abund_Orci_orc, build_sp_tib(original_tib_Orci_orc, 
                                          "Orcinus orca", 
                                          "Orci_orc")),
  tar_target(abund_Pepo_ele, build_sp_tib(original_tib_Pepo_ele, 
                                          "Peponocephala electra", 
                                          "Pepo_ele")),
  tar_target(abund_Phoc_dal, build_sp_tib(original_tib_Phoc_dal, 
                                          "Phocoenoides dalli", 
                                          "Phoc_dal")),
  tar_target(abund_Phoc_pho, build_sp_tib(original_tib_Phoc_pho, 
                                          "Phocoena phocoena", 
                                          "Phoc_pho")),
  tar_target(abund_Phys_mac, build_sp_tib(original_tib_Phys_mac, 
                                          "Physeter macrocephalus", 
                                          "Phys_mac")),
  tar_target(abund_Pseu_cra, build_sp_tib(original_tib_Pseu_cra, 
                                          "Pseudorca crassidens", 
                                          "Pseu_cra")),
  tar_target(abund_Sota_gui, build_sp_tib(original_tib_Sota_gui, 
                                          "Sotalia guianensis", 
                                          "Sota_gui")),
  tar_target(abund_Sten_att, build_sp_tib(original_tib_Sten_att, 
                                          "Stenella attenuata", 
                                          "Sten_att")),
  tar_target(abund_Sten_cly, build_sp_tib(original_tib_Sten_cly, 
                                          "Stenella clymene", 
                                          "Sten_cly")),
  tar_target(abund_Sten_fro, build_sp_tib(original_tib_Sten_fro, 
                                          "Stenella frontalis", 
                                          "Sten_fro")),
  tar_target(abund_Sten_lon, build_sp_tib(original_tib_Sten_lon, 
                                          "Stenella longirostris", 
                                          "Sten_lon")),
  tar_target(abund_Sten_bre, build_sp_tib(original_tib_Sten_bre, 
                                          "Steno bredanensis", 
                                          "Sten_bre")),
  tar_target(abund_Turs_tru, build_sp_tib(original_tib_Turs_tru, 
                                          "Tursiops truncatus", 
                                          "Turs_tru")),
  # cases with mixed-species groups 
  tar_target(abund_Dd_Dc_Sc, build_sp_tib_Dd_Dc_Sc(ratio_full_others)),
  tar_target(abund_BW_sp, build_sp_tib_BW(ratio_full_REMMOAs, ratio_full_others)),
  tar_target(abund_sp_REMMOA_smalldel, build_sp_tib_REMMOA_smalldel(ratio_full_REMMOAs)),
  tar_target(abund_sp_REMMOA_largedel, build_sp_tib_REMMOA_largedel(ratio_full_REMMOAs)),
  tar_target(abund_sp_REMMOA_smallglobi, build_sp_tib_REMMOA_smallglobi(ratio_full_REMMOAs)),
  tar_target(abund_sp_REMMOA_largeglobi, build_sp_tib_REMMOA_largeglobi(ratio_full_REMMOAs)), 
  tar_target(abund_sp_all, rbind(abund_Bala_acu, 
                                 abund_Bala_bor, 
                                 abund_Bala_ede, 
                                 abund_Bala_mus, 
                                 abund_Bala_phy, 
                                 abund_Fere_att, 
                                 abund_Glob_mac, 
                                 abund_Glob_mel, 
                                 abund_Gram_gri, 
                                 abund_Kogi_spp, 
                                 abund_Lage_acu, 
                                 abund_Lage_alb, 
                                 abund_Lage_hos, 
                                 abund_Lage_obl, 
                                 abund_Liss_bor, 
                                 abund_Mega_nov,
                                 abund_Orci_orc, 
                                 abund_Pepo_ele, 
                                 abund_Phoc_dal, 
                                 abund_Phoc_pho, 
                                 abund_Phys_mac, 
                                 abund_Pseu_cra, 
                                 abund_Sota_gui, 
                                 abund_Sten_att, 
                                 abund_Sten_cly, 
                                 abund_Sten_fro, 
                                 abund_Sten_lon,
                                 abund_Sten_bre,
                                 abund_Turs_tru, 
                                 abund_Dd_Dc_Sc, 
                                 abund_BW_sp, 
                                 abund_sp_REMMOA_smalldel,
                                 abund_sp_REMMOA_largedel, 
                                 abund_sp_REMMOA_smallglobi, 
                                 abund_sp_REMMOA_largeglobi) |> 
               dplyr::arrange(Code_sp, Species, Geo_area, Eco_area))
)
